### ISSUE TITLE
crash on startup with syntax error

### ISSUE THREAD

**Issue by markstos** [mihalea/i3expo#5]
```
 i3expo -s
Traceback (most recent call last):
  File "/usr/local/bin/i3expo", line 11, in <module>
    load_entry_point('i3expo==1.1.1', 'console_scripts', 'i3expo')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/i3expo-1.1.1-py2.7.egg/i3expo/client.py", line 16
    with open(f"/var/run/user/{uid}/i3expo.pid", "r") as f:
                                              ^
SyntaxError: invalid syntax
```

Maybe I've done something wrong, but it would be helpful in that case if the script died with a message that give a hint about what needs to be fixed. 

This is on Ubuntu with Python 2.7. If a newer version of Python is required that would be helpful to clarify in the manual install docs. 

Thanks.

**Comment by mihalea** [comment]
This program does indeed require a newer version of Python, specifically 3.5. I have added this information to the readme. I also pushed version 1.1.2 as a hotfix to prevent the client from using Python 2 over Python 3.
